modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="modname"
version="${file.jarVersion}"
displayName="ModName"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/modname"
description=""

[[dependencies.modname]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.7, 2.11)"
    ordering="BEFORE"
    side="BOTH"
