modLoader="javafml"
loaderVersion="[31,)"
license="ARR"

[[mods]]
modId="kaleido"
version="${file.jarVersion}"
displayName="Kaleido"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kaleido"
description='''Models for showcase are from ItemBound by SixFootBlue, and will finally be removed in release ver.
Textures of woodworking bench are made by YurisCat'''

[[dependencies.kaleido]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.8.3, 2.12)"
    ordering="BEFORE"
    side="BOTH"
