modLoader="javafml"
loaderVersion="[35,)"
license="ARR"

[[mods]]
modId="kaleido"
version="${file.jarVersion}"
displayName="Kaleido"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kaleido"
description='''Community-oriented decorations & building blocks mod. Datapack item & block maker.
Textures of woodworking bench are made by YurisCat'''

[[dependencies.kaleido]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.4, 3.9)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.kaleido]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.4, )"
    ordering="NONE"
    side="BOTH"
