package moe.mmf.csscolors.keywords;

import java.util.HashMap;
import java.util.Map;

public abstract class CSSLevel3 {
    public static final Map<String, String> colors = new HashMap<String, String>() {{
        put("aliceblue", aliceblue);
        put("antiquewhite", antiquewhite);
        put("aquamarine", aquamarine);
        put("azure", azure);
        put("beige", beige);
        put("bisque", bisque);
        put("blanchedalmond", blanchedalmond);
        put("blueviolet", blueviolet);
        put("brown", brown);
        put("burlywood", burlywood);
        put("cadetblue", cadetblue);
        put("chartreuse", chartreuse);
        put("chocolate", chocolate);
        put("coral", coral);
        put("cornflowerblue", cornflowerblue);
        put("cornsilk", cornsilk);
        put("crimson", crimson);
        put("cyan", CSSLevel1.aqua);
        put("darkblue", darkblue);
        put("darkcyan", darkcyan);
        put("darkgoldenrod", darkgoldenrod);
        put("darkgray", darkgray);
        put("darkgreen", darkgreen);
        put("darkgrey", darkgray);
        put("darkkhaki", darkkhaki);
        put("darkmagenta", darkmagenta);
        put("darkolivegreen", darkolivegreen);
        put("darkorange", darkorange);
        put("darkorchid", darkorchid);
        put("darkred", darkred);
        put("darksalmon", darksalmon);
        put("darkseagreen", darkseagreen);
        put("darkslateblue", darkslateblue);
        put("darkslategray", darkslategray);
        put("darkslategrey", darkslategray);
        put("darkturquoise", darkturquoise);
        put("darkviolet", darkviolet);
        put("deeppink", deeppink);
        put("deepskyblue", deepskyblue);
        put("dimgray", dimgray);
        put("dimgrey", dimgray);
        put("dodgerblue", dodgerblue);
        put("firebrick", firebrick);
        put("floralwhite", floralwhite);
        put("forestgreen", forestgreen);
        put("gainsboro", gainsboro);
        put("ghostwhite", ghostwhite);
        put("gold", gold);
        put("goldenrod", goldenrod);
        put("greenyellow", greenyellow);
        put("grey", CSSLevel1.gray);
        put("honeydew", honeydew);
        put("hotpink", hotpink);
        put("indianred", indianred);
        put("indigo", indigo);
        put("ivory", ivory);
        put("khaki", khaki);
        put("lavender", lavender);
        put("lavenderblush", lavenderblush);
        put("lawngreen", lawngreen);
        put("lemonchiffon", lemonchiffon);
        put("lightblue", lightblue);
        put("lightcoral", lightcoral);
        put("lightcyan", lightcyan);
        put("lightgoldenrodyellow", lightgoldenrodyellow);
        put("lightgray", lightgray);
        put("lightgreen", lightgreen);
        put("lightgrey", lightgray);
        put("lightpink", lightpink);
        put("lightsalmon", lightsalmon);
        put("lightseagreen", lightseagreen);
        put("lightskyblue", lightskyblue);
        put("lightslategray", lightslategray);
        put("lightslategrey", lightslategray);
        put("lightsteelblue", lightsteelblue);
        put("lightyellow", lightyellow);
        put("limegreen", limegreen);
        put("linen", linen);
        put("magenta", CSSLevel1.fuchsia);
        put("mediumaquamarine", mediumaquamarine);
        put("mediumblue", mediumblue);
        put("mediumorchid", mediumorchid);
        put("mediumpurple", mediumpurple);
        put("mediumseagreen", mediumseagreen);
        put("mediumslateblue", mediumslateblue);
        put("mediumspringgreen", mediumspringgreen);
        put("mediumturquoise", mediumturquoise);
        put("mediumvioletred", mediumvioletred);
        put("midnightblue", midnightblue);
        put("mintcream", mintcream);
        put("mistyrose", mistyrose);
        put("moccasin", moccasin);
        put("navajowhite", navajowhite);
        put("oldlace", oldlace);
        put("olivedrab", olivedrab);
        put("orangered", orangered);
        put("orchid", orchid);
        put("palegoldenrod", palegoldenrod);
        put("palegreen", palegreen);
        put("paleturquoise", paleturquoise);
        put("palevioletred", palevioletred);
        put("papayawhip", papayawhip);
        put("peachpuff", peachpuff);
        put("peru", peru);
        put("pink", pink);
        put("plum", plum);
        put("powderblue", powderblue);
        put("rosybrown", rosybrown);
        put("royalblue", royalblue);
        put("saddlebrown", saddlebrown);
        put("salmon", salmon);
        put("sandybrown", sandybrown);
        put("seagreen", seagreen);
        put("seashell", seashell);
        put("sienna", sienna);
        put("skyblue", skyblue);
        put("slateblue", slateblue);
        put("slategray", slategray);
        put("slategrey", slategray);
        put("snow", snow);
        put("springgreen", springgreen);
        put("steelblue", steelblue);
        put("tan", tan);
        put("thistle", thistle);
        put("tomato", tomato);
        put("turquoise", turquoise);
        put("violet", violet);
        put("wheat", wheat);
        put("whitesmoke", whitesmoke);
        put("yellowgreen", yellowgreen);
    }};


    public static final String aliceblue = "#f0f8ff";
    public static final String antiquewhite = "#faebd7";
    public static final String aquamarine = "#7fffd4";
    public static final String azure = "#f0ffff";
    public static final String beige = "#f5f5dc";
    public static final String bisque = "#ffe4c4";
    public static final String blanchedalmond = "#ffebcd";
    public static final String blueviolet = "#8a2be2";
    public static final String brown = "#a52a2a";
    public static final String burlywood = "#deb887";
    public static final String cadetblue = "#5f9ea0";
    public static final String chartreuse = "#7fff00";
    public static final String chocolate = "#d2691e";
    public static final String coral = "#ff7f50";
    public static final String cornflowerblue = "#6495ed";
    public static final String cornsilk = "#fff8dc";
    public static final String crimson = "#dc143c";
    public static final String darkblue = "#00008b";
    public static final String darkcyan = "#008b8b";
    public static final String darkgoldenrod = "#b8860b";
    public static final String darkgray = "#a9a9a9";
    public static final String darkgreen = "#006400";
    public static final String darkkhaki = "#bdb76b";
    public static final String darkmagenta = "#8b008b";
    public static final String darkolivegreen = "#556b2f";
    public static final String darkorange = "#ff8c00";
    public static final String darkorchid = "#9932cc";
    public static final String darkred = "#8b0000";
    public static final String darksalmon = "#e9967a";
    public static final String darkseagreen = "#8fbc8f";
    public static final String darkslateblue = "#483d8b";
    public static final String darkslategray = "#2f4f4f";
    public static final String darkturquoise = "#00ced1";
    public static final String darkviolet = "#9400d3";
    public static final String deeppink = "#ff1493";
    public static final String deepskyblue = "#00bfff";
    public static final String dimgray = "#696969";
    public static final String dodgerblue = "#1e90ff";
    public static final String firebrick = "#b22222";
    public static final String floralwhite = "#fffaf0";
    public static final String forestgreen = "#228b22";
    public static final String gainsboro = "#dcdcdc";
    public static final String ghostwhite = "#f8f8ff";
    public static final String gold = "#ffd700";
    public static final String goldenrod = "#daa520";
    public static final String greenyellow = "#adff2f";
    public static final String honeydew = "#f0fff0";
    public static final String hotpink = "#ff69b4";
    public static final String indianred = "#cd5c5c";
    public static final String indigo = "#4b0082";
    public static final String ivory = "#fffff0";
    public static final String khaki = "#f0e68c";
    public static final String lavender = "#e6e6fa";
    public static final String lavenderblush = "#fff0f5";
    public static final String lawngreen = "#7cfc00";
    public static final String lemonchiffon = "#fffacd";
    public static final String lightblue = "#add8e6";
    public static final String lightcoral = "#f08080";
    public static final String lightcyan = "#e0ffff";
    public static final String lightgoldenrodyellow = "#fafad2";
    public static final String lightgray = "#d3d3d3";
    public static final String lightgreen = "#90ee90";
    public static final String lightpink = "#ffb6c1";
    public static final String lightsalmon = "#ffa07a";
    public static final String lightseagreen = "#20b2aa";
    public static final String lightskyblue = "#87cefa";
    public static final String lightslategray = "#778899";
    public static final String lightsteelblue = "#b0c4de";
    public static final String lightyellow = "#ffffe0";
    public static final String limegreen = "#32cd32";
    public static final String linen = "#faf0e6";
    public static final String mediumaquamarine = "#66cdaa";
    public static final String mediumblue = "#0000cd";
    public static final String mediumorchid = "#ba55d3";
    public static final String mediumpurple = "#9370db";
    public static final String mediumseagreen = "#3cb371";
    public static final String mediumslateblue = "#7b68ee";
    public static final String mediumspringgreen = "#00fa9a";
    public static final String mediumturquoise = "#48d1cc";
    public static final String mediumvioletred = "#c71585";
    public static final String midnightblue = "#191970";
    public static final String mintcream = "#f5fffa";
    public static final String mistyrose = "#ffe4e1";
    public static final String moccasin = "#ffe4b5";
    public static final String navajowhite = "#ffdead";
    public static final String oldlace = "#fdf5e6";
    public static final String olivedrab = "#6b8e23";
    public static final String orangered = "#ff4500";
    public static final String orchid = "#da70d6";
    public static final String palegoldenrod = "#eee8aa";
    public static final String palegreen = "#98fb98";
    public static final String paleturquoise = "#afeeee";
    public static final String palevioletred = "#db7093";
    public static final String papayawhip = "#ffefd5";
    public static final String peachpuff = "#ffdab9";
    public static final String peru = "#cd853f";
    public static final String pink = "#ffc0cb";
    public static final String plum = "#dda0dd";
    public static final String powderblue = "#b0e0e6";
    public static final String rosybrown = "#bc8f8f";
    public static final String royalblue = "#4169e1";
    public static final String saddlebrown = "#8b4513";
    public static final String salmon = "#fa8072";
    public static final String sandybrown = "#f4a460";
    public static final String seagreen = "#2e8b57";
    public static final String seashell = "#fff5ee";
    public static final String sienna = "#a0522d";
    public static final String skyblue = "#87ceeb";
    public static final String slateblue = "#6a5acd";
    public static final String slategray = "#708090";
    public static final String snow = "#fffafa";
    public static final String springgreen = "#00ff7f";
    public static final String steelblue = "#4682b4";
    public static final String tan = "#d2b48c";
    public static final String thistle = "#d8bfd8";
    public static final String tomato = "#ff6347";
    public static final String turquoise = "#40e0d0";
    public static final String violet = "#ee82ee";
    public static final String wheat = "#f5deb3";
    public static final String whitesmoke = "#f5f5f5";
    public static final String yellowgreen = "#9acd32";
}
